TestPaper/Controllers/PartialViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestPaper.Controllers
{
    public class PartialViewController : Controller
    {
        //无关代码
        // GET: PartialView
        public ActionResult Index()
        {
            return View();
        }  
        public PartialViewResult ChildAction(DateTime time )
        {
            string greetings = string.Empty;
            if (time.Hour > 18)
            {
                greetings = "Good Eventing .NOW is " + time.ToString("HH:mm:ss");
            }else if (time.Hour > 12)
            {
                greetings = "Good afternoon. Now is " + time.ToString("HH:mm:ss");
            }
            else
            {
                greetings = "Good morning. Now is " + time.ToString("HH:mm:ss");
            }
            return PartialView("ChildAction", greetings);
        }
    }
}

TestPaper/Views/PartialView/ChildAction.cshtml
@model string 
@{
    ViewBag.Title = "ChildAction";
}
<h2>@Model</h2>
<h2>ChildAction</h2>

TestPaper/Views/PartialView/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/jquery-1.10.2.js"></script>
<h2>Before PartialView</h2>
<hr/>
@Html.Partial("PartialPage",1)
@Html.Action("ChildAction", new { time=DateTime.Now})
<hr />
@{ 
    Html.RenderPartial("PartialPage",2);
    Html.RenderAction("ChildAction", new { time = DateTime.Now.AddHours(12) });
}
<hr />
<h2>After PartialView</h2>
<script>
    setInterval(LoadAction,1000);
    function LoadAction() {
        var time = new date();
        $.ajax({
            type: "POST",
            url: '@Url.Action("ChildAction", "PartialView")',
            data: { time: time.getHours() + ":" + time.getMinutes() + ":" + tim.getSeconds() },
            datatype: "json",
            success: function (data) {
                $('#header').html(data);
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert(errorThrown);
            }
        })
    }
</script>