TestPaper/Controllers/FillQuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestPaper.Dal;
using TestPaper.Models;

namespace TestPaper.Controllers
{
    public class FillQuestionsController : Controller
    {
        private TestPaperContext db = new TestPaperContext();

        // GET: FillQuestions
        public ActionResult Index()
        {
            return View(db.FillQuestions.ToList());
        }

        // GET: FillQuestions/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FillQuestion fillQuestion = db.FillQuestions.Find(id);
            if (fillQuestion == null)
            {
                return HttpNotFound();
            }
            return View(fillQuestion);
        }

        // GET: FillQuestions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FillQuestions/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Options,Answer,Score,Subject,Section,Difficulty")] FillQuestion fillQuestion)
        {
            if (ModelState.IsValid)
            {
                fillQuestion.Id = Guid.NewGuid();
                db.FillQuestions.Add(fillQuestion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(fillQuestion);
        }

        // GET: FillQuestions/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FillQuestion fillQuestion = db.FillQuestions.Find(id);
            if (fillQuestion == null)
            {
                return HttpNotFound();
            }
            return View(fillQuestion);
        }

        // POST: FillQuestions/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Options,Answer,Score,Subject,Section,Difficulty")] FillQuestion fillQuestion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fillQuestion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(fillQuestion);
        }

        // GET: FillQuestions/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FillQuestion fillQuestion = db.FillQuestions.Find(id);
            if (fillQuestion == null)
            {
                return HttpNotFound();
            }
            return View(fillQuestion);
        }

        // POST: FillQuestions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            FillQuestion fillQuestion = db.FillQuestions.Find(id);
            db.FillQuestions.Remove(fillQuestion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        /// <summary>
        /// 根据试卷课题、章节、难易程度进行筛选
        /// </summary>
        /// <param name="testpaperid">试卷序号</param>
        /// <param name="testtype">试卷类型</param>
        /// <param name="subject">课题</param>
        /// <param name="section">章节</param>
        /// <param name="diffcult">难易度</param>
        /// <returns>分布视图</returns>
        public PartialViewResult GetTestQuestionInfoByType( int testpaperid ,string testtype, string subject, string section, string diffcult )
        {
            ViewData["TestType"] = testtype;
            ViewData["testpaperid"] = testpaperid;
            ViewData["TestType"] = testtype;
            ViewData["subject"] = subject;
            ViewData["section"] = section;
            ViewData["diffcult"] = diffcult;
            var fliiquestion = db.FillQuestions.Where(u => true);
            if (subject != null)
            {
                fliiquestion = fliiquestion.Where(u => u.Subject.Contains(subject));
            }
            if (section != null)
            {
                fliiquestion = fliiquestion.Where(u => u.Section.Contains(section));
            }
            if (diffcult != null)
            {
                fliiquestion = fliiquestion.Where(u => u.Difficulty.Contains(diffcult));
            }
            return PartialView("ChildAction", fliiquestion.ToList());
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestPaper/Controllers/TestPaperInfoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TestPaper.Dal;
using TestPaper.Models;

namespace TestPaper.Controllers
{
    public class TestPaperInfoesController : Controller
    {
        private TestPaperContext db = new TestPaperContext();

        // GET: TestPaperInfoes
        public ActionResult Index()
        {
            return View(db.TestPaperInfoes.ToList());
        }

        // GET: TestPaperInfoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TestPaperInfo testPaperInfo = db.TestPaperInfoes.Find(id);
            if (testPaperInfo == null)
            {
                return HttpNotFound();
            }
            return View(testPaperInfo);
        }

        // GET: TestPaperInfoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TestPaperInfoes/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] TestPaperInfo testPaperInfo)
        {
            if (ModelState.IsValid)
            {
                db.TestPaperInfoes.Add(testPaperInfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(testPaperInfo);
        }

        // GET: TestPaperInfoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TestPaperInfo testPaperInfo = db.TestPaperInfoes.Find(id);
            if (testPaperInfo == null)
            {
                return HttpNotFound();
            }
            return View(testPaperInfo);
        }

        // POST: TestPaperInfoes/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] TestPaperInfo testPaperInfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(testPaperInfo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(testPaperInfo);
        }

        // GET: TestPaperInfoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TestPaperInfo testPaperInfo = db.TestPaperInfoes.Find(id);
            if (testPaperInfo == null)
            {
                return HttpNotFound();
            }
            return View(testPaperInfo);
        }

        // POST: TestPaperInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TestPaperInfo testPaperInfo = db.TestPaperInfoes.Find(id);
            db.TestPaperInfoes.Remove(testPaperInfo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        /// <summary>
        /// 返回添加试卷页面
        /// </summary>
        /// <param name="id">试卷序号</param>
        /// <param name="testType">跳转前的试卷类型</param>
        /// <param name="subject">跳转前的试题科目</param>
        /// <param name="section">跳转前的试题章节</param>
        /// <param name="diffcult">跳转前的试题难易程度</param>
        /// <returns></returns>
        public ActionResult AddQuestions(int ? id,string  testType , string subject, string section, string diffcult )
        {
            ViewData["testType"] = testType;
            ViewData["subject"] = subject;
            ViewData["section"] = section;
            ViewData["diffcult"] = diffcult;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TestPaperInfo testPaperInfo = db.TestPaperInfoes.Find(id);
            if (testPaperInfo == null)
            {
                return HttpNotFound();
            }
            return View(testPaperInfo);
        }
        /// <summary>
        /// 添加试题
        /// </summary>
        /// <param name="id">试题id</param>
        /// <param name="testpaperid">试卷id</param>
        /// <param name="testType">跳转前的试卷类型</param>
        /// <param name="subject">跳转前的试题科目</param>
        /// <param name="section">跳转前的试题章节</param>
        /// <param name="diffcult">跳转前的试题难易程度</param>
        /// <returns></returns>
        public ActionResult Add(Guid? id,int ? testpaperid ,string type,string subject,string section,string diffcult  )
        {
            TestPaperInfo testPaperInfo = db.TestPaperInfoes.Find(testpaperid);

            switch (type)
            {
                case "选择题":
                    ChoiceQuestion choicequestion = db.ChoiceQuestions.Find(id);
                    testPaperInfo.ChoiceQuestions.Add(choicequestion);
                    break;
                case "填空题":
                    FillQuestion fillquestion = db.FillQuestions.Find(id);
                    testPaperInfo.FillQuestions.Add(fillquestion);
                    break;
                case "判断题":
                    CheckQuestion checkquestion = db.CheckQuestions.Find(id);
                    testPaperInfo.CheckQuestions.Add(checkquestion);
                    break;
                case "计算题":
                    CalculateQuestion calculatate = db.CalculateQuestion.Find(id);
                    testPaperInfo.CalculateQuestions.Add(calculatate);
                    break;
            }
            db.SaveChanges();//保存数据
            //返回到添加试题页面
            return RedirectToAction("AddQuestions",new { id = testpaperid ,testType= type, subject =subject, section = section, diffcult = diffcult });
        }
        public ActionResult ChildView(int ? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TestPaperInfo testPaperInfo = db.TestPaperInfoes.Find(id);
            if (testPaperInfo == null)
            {
                return HttpNotFound();
            }
            return View(testPaperInfo);
        }
        [ValidateInput(false)]
        [HttpPost]
        public FileResult ExportWord(string html )
        {
            StringBuilder sb = new StringBuilder();
            sb.Append(html);
            var byteArray = System.Text.Encoding.Default.GetBytes(sb.ToString());
            Response.ContentEncoding = System.Text.Encoding.GetEncoding("gb2312");
            return File(byteArray, "application/ms-word", "TestPaper" + ".doc");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestPaper/Views/TestPaperListInfo/Create.cshtml
@model TestPaper.Models.TestPaperInfo

@{
    ViewBag.Title = "保存";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/jquery-1.10.2.js"></script>
<h2>保存</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="form-horizontal col-sm-3">
            <h4>TestPaperInfo</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2 " })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })                  
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-offset-2 col-md-10">
                    @Html.DropDownList("TestType", new[] { new SelectListItem() { Text = "选择题" }, new SelectListItem() { Text = "判断题" }, new SelectListItem() { Text = "填空题" }, new SelectListItem() { Text = "解答题" } }, new { @class = "form-control" })
                </div>
            </div>

        </div>
        <div class="col-sm-9" id="Questions">
        </div>
    </div>
    <div class="container" id="Choice">
        <h4>选择题</h4>
        @{ Html.RenderAction("Index", "TestPaperInfoes");}
    </div>
    <div class="container" id="Fill">
        <h4>填空题</h4>
        @{ Html.RenderAction("Index", "FillQuestions");}
    </div>
    <div class="container col-md-offset-2 col-md-10">
        @Html.ActionLink("Back to List", "Index")
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 ">
            <input type="submit" value="Create" class="btn btn-default" /><div id="div1" style="display:none">请稍后</div>
        </div>
    </div>
}


@Scripts.Render("~/bundles/jquery")
<script type="text/javascript">
    $(document).ready(function () {
        GetQuestionInfo();
        $("#TestType").change(function () {
            GetQuestionInfo();
        })
    })
    function GetQuestionInfo() {
        var testtitle = "";
        var temp = $("#TestType").val();
        switch (temp) {
            case "选择题":
                $.ajax({
                    async: true,
                    type: "Post",
                    url: "/ChoiceQuestions/GetTestQuestionInfoByType",
                    LoadingElementId: "div1",
                    success: function (data) {
                        $("#Questions").html(data);
                    }

                })
                break;
            case "填空题":
                $.ajax({
                    type: "Post",
                    url: "/FillQuestions/GetTestQuestionInfoByType",
                    success: function (data) {
                        $("#Questions").html(data);
                    }

                })
                break;

        }
    }
 
       
</script>

TestPaper/Views/TestPaperListInfo/Delete.cshtml
@model TestPaper.Models.TestPaperInfo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TestPaperInfo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TestPaper/Views/TestPaperListInfo/Details.cshtml
@model TestPaper.Models.TestPaperInfo

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TestPaperInfo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TestPaper/Views/TestPaperListInfo/Edit.cshtml
@model TestPaper.Models.TestPaperInfo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TestPaperInfo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TestPaper/Views/TestPaperListInfo/Index.cshtml
@model IEnumerable<TestPaper.Models.TestPaperInfo>

@{
    ViewBag.Title = "试卷信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>